# Created using wingetcreate 1.0.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Autodesk.ShotGridRV2022.2.0
PackageVersion: 22.2.0
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: wix
  InstallerUrl: https://sg-software.ems.autodesk.com/deploy/rv/Current_Release/rv-win64-x86-64-2022.2.0.msi
  InstallerSha256: D6E54211DA96894F22C68179A6BD24A01AEAF99E5395C397EAD7C1040DE02834
  ProductCode: '{F595D143-2DB2-4F46-B975-F562CC082EEF}'
ManifestType: installer
ManifestVersion: 1.1.0

